import base64
import argparse
from email.mime.text import MIMEText

import google.auth
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

import os, sys
from pathlib import Path

secrets_folder = str(Path.home()) + '/secrets/'

set_args = {}
for prop in ["auto_email", "admin_email", "system_name"]:
    with open(secrets_folder + prop + ".txt", "r") as f:
        set_args[prop] = f.read()
        while not set_args[prop][-1].isalnum():
            set_args[prop] = set_args[prop][:-1]

SCOPES = ['https://mail.google.com/', 'https://www.googleapis.com/auth/gmail.send']
SERVICE_ACCOUNT_FILE = secrets_folder + "gmail_key.json"

credentials = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE, scopes=SCOPES)

delegated_credentials = credentials.with_subject(set_args["auto_email"])

def gmail_send_message(address, msg_path):
    with open(msg_path, "r") as f:
        msg = f.read()
    subject = msg[:msg.index("\n")]
    msg = msg[msg.index("\n") + 1:]

    msg += "\n\n -----------------------------------------------------------------------------";
    msg += f"\n This is an automated email generated by {set_args['system_name']}.";
    msg += "\n If you are experiencing issues with the system, please contact the webmaster at " + set_args["admin_email"] + ".";

    service = build('gmail', 'v1', credentials=delegated_credentials)
    message = MIMEText(msg)
    message['To'] = address
    message['From'] = f'{set_args["system_name"]} <{set_args["auto_email"]}>'
    message['Subject'] = subject

    encoded_message = base64.urlsafe_b64encode(message.as_bytes()) \
        .decode()

    send_message = (service.users().messages().send
                    (userId="me", body={ 'raw': encoded_message }).execute())

    os.remove(msg_path)
    return send_message


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Send email')

    parser.add_argument('--address', type=str)
    parser.add_argument('--msg_path', type=str)

    args = parser.parse_args()
    gmail_send_message(args.address, args.msg_path)
